#!/usr/bin/python
'''
ronnie = {'Name': 'minnu', 'Age': 7}
print("Student name is {0} and his age is {1}" .format("Naresh",7))
print ("Length : %d" % len(ronnie)) # len() is function
dict_1 = {'Name': 'minnu', 'Age': 7}
print ("Equivalent String : %s" % str(dict_1))  # str() is function
dict_2 = {'Name': 'minnu', 'Age': 7}
print ("Variable Type : %s" %  type(dict_2)) # type() is function
dict_3 = {'Name': 'minnu', 'Age': 7};
print ("Start Len : %d" %  len(dict_3))
'''
#dict.clear()   # clear() is method
#print ("End Len : %d" %  len(dict_3))

dict_4 = {'Name': 'minnu', 'Age': 7}

dict_5 = dict_4.copy() # copy() is method

print ("New dictinary : %s" % str(dict_5))

dict_5.clear()

print ("New dictinary : %s" % str(dict_5))
