#!/usr/bin/python
import smtplib

sender = 'root@mailserver.ucator.com'
receivers = ['kk@mailserver.ucator.com']

message = """From: From Person <root@mailserver.ucator.com>
To: To Person <kk@mailserver.ucator.com>
Subject: SMTP e-mail test
This is a test e-mail message.
"""

try:
   smtpObj = smtplib.SMTP('localhost')
   smtpObj.sendmail(sender, receivers, message)         
   print ("Successfully sent email")
except SMTPException:
   print ("Error: unable to send email")
